In [1]:
import numpy as np

In [8]:
# 1.	Array Creation
# 	    Create a 1D array of numbers from 10 to 50.
#   	Create a 3x3 array of random numbers between 0 and 1.
ar1 = np.array(range(10,51))
print(ar1,'\n')
ar2 = np.random.rand(3, 3)
print(ar2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50] 

[[0.69316199 0.11010451 0.65839563]
 [0.9954708  0.52873292 0.27896688]
 [0.26784034 0.10733983 0.31889234]]


In [5]:
# 2.	Array Attributes
#    	Find the shape, size, and data type of the array you created in the previous task.
print(ar1.shape)
print(ar1.size)
print(ar1.dtype)

(41,)
41
int32


In [7]:
# 3.	Basic Operations
#   	Add 5 to every element of a 1D array.
#       Multiply two 2D arrays element-wise.
ar3 = np.array([1,2,3,4,5])
print(ar3+5,"\n")

ar4 = np.array([[3,5,7],[5,6,7]])
ar5 = np.array([[8,9,0],[2,4,6]])
print(ar4*ar5)

[ 6  7  8  9 10] 

[[24 45  0]
 [10 24 42]]


In [17]:
# 4.	Indexing and Slicing
#   	Create a 5x5 array of integers from 1 to 25. Extract:
#   	The first row.
#   	The last column.
#   	A subarray of the first three rows and first two columns.
ar6 = np.array(range(1,26)).reshape(5,5)
print(ar6,'\n')
print(ar6[0,:],'\n')
print(ar6[:,-1],'\n')
print(ar6[:3,:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[1 2 3 4 5] 

[ 5 10 15 20 25] 

[[ 1  2]
 [ 6  7]
 [11 12]]


In [21]:
# 5.	Aggregation
#   	Create a 10-element array of random integers between 1 and 100. Find:
#   	The maximum value.
#   	The minimum value.
#   	The mean and standard deviation.
ar7 = np.random.randint(1,101,10)
print(ar7,'\n')
print(np.max(ar7),'\n')
print(np.min(ar7),'\n')
print(np.mean(ar7),'\n')
print(np.std(ar7))

[94 94 57 87 35 38 89 73 34 85] 

94 

34 

68.6 

23.938253904577085


In [22]:
# 6.	Reshaping
#   	Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
ar8 = np.array(range(1,13)).reshape(3,4)
print(ar8)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
# 7.	Broadcasting
#   	Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
ar9 = np.ones((3,3))
ar10 = np.array([1,2,3])
res = ar9+ar10
print(res)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [24]:
# 8.	Filtering
#   	Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
ar11 = np.random.randint(1, 51, 20)
res = ar11[ar11 % 5 == 0]
print(res)

[25 15 15 10]


In [26]:
# 9.	Matrix Multiplication
#   	Create two 2x2 matrices and perform matrix multiplication.
ar12 = np.array([[3,5],[5,7]])
ar13 = np.array([[8,9],[2,4]])
print(ar12*ar13)

[[24 45]
 [10 28]]


In [27]:
# 10.	Advanced Indexing
#   	Given a 4x4 array, use fancy indexing to extract the diagonal elements.
ar14 = np.arange(1, 17).reshape(4, 4)
res = ar14[np.arange(4), np.arange(4)]
print(res)

[ 1  6 11 16]
